// This file is auto-generated by @hey-api/openapi-ts

export type Specification = {
  api_key_id: string | null
  actor: string | null
  actor_id: string | null
  branch: string | null
  branch_base: string | null
  ci_platform: string | null
  commit_sha: string | null
  creator_user_id: string | null
  created_at: string
  event_name: string | null
  id: string
  job: string | null
  project_id: string
  ref: string | null
  ref_type: string | null
  repository: string | null
  run_id: string | null
  run_number: string | null
  updated_at: string
  tags: Array<string>
  version: string | null
  workflow: string | null
}

export type PostV1SpecificationsData = {
  body: {
    actor?: string
    actor_id?: string
    branch?: string
    branch_base?: string
    ci_platform?: string
    commit_sha?: string
    default_branch?: string
    dry_run?: string
    event_name?: string
    job?: string
    ref?: string
    ref_type?: string
    repository?: string
    run_id?: string
    run_number?: string
    specification: Blob | File
    tags?: string
    workflow?: string
  }
  path?: never
  query?: never
  url: '/v1/specifications'
}

export type PostV1SpecificationsErrors = {
  /**
   * Unauthorized
   */
  401: {
    error: {
      message: string
      request_id: string
      status: number
      timestamp: string
    }
  }
  /**
   * Forbidden
   */
  403: {
    error: {
      message: string
      request_id: string
      status: number
      timestamp: string
    }
  }
  /**
   * Content Too Large
   */
  413: {
    error: {
      message: string
      request_id: string
      status: number
      timestamp: string
    }
  }
}

export type PostV1SpecificationsError =
  PostV1SpecificationsErrors[keyof PostV1SpecificationsErrors]

export type PostV1SpecificationsResponses = {
  /**
   * OK
   */
  200: Specification
}

export type PostV1SpecificationsResponse =
  PostV1SpecificationsResponses[keyof PostV1SpecificationsResponses]

export type ClientOptions = {
  baseUrl: string
}
